<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { api } from '../api/client'; import ChatPanel from '../components/ChatPanel.vue'; import ConfirmDialog from '../components/ConfirmDialog.vue'; import SourceDrawer from '../components/SourceDrawer.vue'; import SessionList, { type SessionSummary } from '../components/SessionList.vue'
const route=useRoute(),router=useRouter(),sessions=ref<SessionSummary[]>([]),current=ref(String(route.params.id||'')),source=ref<Record<string,unknown>|null>(null),error=ref(''),pendingDelete=ref(''),deleting=ref(false)
async function load(){try{sessions.value=(await api<{items:SessionSummary[]}>('/api/sessions')).items;const exists=sessions.value.some(item=>item.id===current.value);if(!exists){current.value=sessions.value[0]?.id??'';await router.replace(current.value?`/chat/${current.value}`:'/')}}catch(e){error.value=e instanceof Error?e.message:'会话读取失败'}}
async function create(){const s=await api<SessionSummary>('/api/sessions',{method:'POST',body:JSON.stringify({title:'新会话'})});sessions.value.unshift(s);current.value=s.id;router.push(`/chat/${s.id}`)}
async function remove(){if(!pendingDelete.value||deleting.value)return;deleting.value=true;try{await api(`/api/sessions/${pendingDelete.value}`,{method:'DELETE'});pendingDelete.value='';await load()}catch(e){error.value=e instanceof Error?e.message:'删除失败'}finally{deleting.value=false}}
function choose(id:string){current.value=id;router.push(`/chat/${id}`)} onMounted(load)
</script>
<template><div class="chat-view"><p v-if="error" class="error">{{error}}</p><div class="chat-page"><SessionList :sessions="sessions" :current-id="current" @create="create" @choose="choose" @remove="pendingDelete=$event"/><ChatPanel v-if="current" :session-id="current" @source-open="source=$event"/><div v-else class="empty-panel"><button class="primary" @click="create">新建对话</button><p>从今天吃什么开始。</p></div><SourceDrawer :source="source" @close="source=null"/><ConfirmDialog :open="!!pendingDelete" title="删除会话？" description="这个会话和其中的全部消息将被删除。" :busy="deleting" @cancel="pendingDelete=''" @confirm="remove"/></div></div></template>
